Add API to validate a Flag value without setting it
yugabyte/gflags pull request #5
Opened 2024-06-15 00:34 UTC by hari90

Adding `ValidateCommandLineOption` that validates a flag value without actually setting it. This will be useful to prevent processes crashes that currently arises from setting incorrect values, by validating the flag for use before setting it.

Test improvement:
Added `test_filter` flag for filtering and running a single unit test.

Test Plan:
> ./build_and_test.sh; _build/bin/gflags_unittest --test_filter ValidateFlagValueTest/BaseTest
> 
> Running the unit tests now...
> 
> Running test ValidateFlagValueTest/BaseTest
> test_flag isn't 5!
> 
> Passed 1 tests
> 
> PASS

2024-06-17 21:45 UTC, SrivastavaAnubhav requested changes

2024-06-17 21:45 UTC, SrivastavaAnubhav commented on src/gflags.cc
> +    *err_msg = "";
On success, why would there be an error message?

2024-06-17 21:45 UTC, SrivastavaAnubhav commented on src/util.h
> +    fprintf(stderr, "\nPassed %d tests\n\nPASS\n", tests_run);      \
Print number of skipped tests as well

2024-06-17 21:45 UTC, SrivastavaAnubhav commented on src/util.h
> +          strcasecmp(FLAGS_test_filter.c_str(), (#a "/" #b)) != 0) {                      \
Please add a comment here for the macro illiterate of us

2024-06-17 21:45 UTC, SrivastavaAnubhav commented on test/gflags_unittest.cc
> +  EXPECT_EQ("initial", FLAGS_test_str1);
ASSERT_EQ here and below

2024-06-17 21:45 UTC, SrivastavaAnubhav commented on test/gflags_unittest.cc
> +  }
Same case as above. Remove?

2024-06-17 21:45 UTC, SrivastavaAnubhav commented on test/gflags_unittest.cc
> +  if (run_tests || !FLAGS_test_filter.empty()) {
Why is the added code necessary?

2024-06-17 23:26 UTC, hari90 commented on test/gflags_unittest.cc
> +  EXPECT_EQ("initial", FLAGS_test_str1);
We dont have gtest. This is a custom macro which dos not have 'ASSERT_EQ'

2024-06-18 17:05 UTC, SrivastavaAnubhav commented on test/gflags_unittest.cc
> +  if (run_tests || !FLAGS_test_filter.empty()) {
Where is the entry point for the code that runs only the filtered tests?

2024-06-18 17:07 UTC, SrivastavaAnubhav approved these changes

2024-06-18 23:20 UTC, merged